name: eers
on:
  push:
    branches:
      - master

env:
  name: Vache Yerjnaik Aqob

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Hello, this is a message from the eers workflow!"
      - name: Fetch GitHub username
        run: echo "My name is $name"
