name: eers
on:
  push:
    branches:
      - master

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Hello, this is a message from the eers workflow!"
